name: kevin_test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#8b011b'
    - '#d6d837'
    - '#cd9c8d'
    - '#7f4c3d'
  brandStrength: 0.6126629076898098
  lightness: 0.8611913262866437
  saturation: 0.2631885604932904
  rhythmicContrast: 0.5863296075258404
purpose: []
